#!/uns/bin/zsh -f
f=$1
print -u2 "Making xml-unparsed/$f.xml"
jikes +ux $f
print -u2 "Converting back to back-converted/$f"
xt xml-unparsed/$f.xml pretty-printer.xsl > back-converted/$f
cd back-converted
print -u2 "Making back-converted/xml-unparsed/$f.xml"
jikes +ux $f
print -u2 "Comparing the two (canonicalized) JavaML files..."
diff -u =(perl -pe 's/(locvar|frmarg|meth)-\d+/$1/g' ../xml-unparsed/$f.xml) \
        =(perl -pe 's/(locvar|frmarg|meth)-\d+/$1/g' xml-unparsed/$f.xml)  && \
   echo "Success! No differences found."



