#!/usr/bin/perl -w
# $Id$
# Copyright (C) 2000 Greg J. Badros, <gjb@cs.washington.edu>
# http://www.cs.washington.edu/homes/gjb/JavaML
#
# Simple example of using the DOM on the JavaML representation
# to list all the methods in a code database
#

use XML::DOM;

my $filename = shift @ARGV;

my $parser = new XML::DOM::Parser;
my $doc = $parser->parsefile ($filename);

# print all NAME attributes of all method elements
my $nodes = $doc->getElementsByTagName("method");
my $n = $nodes->getLength();

print "$n methods...\n";

for (my $i = 0; $i < $n; $i++) {	
  my $node = $nodes->item ($i);	
  my $name = $node->getAttribute("name");
#  $node->setAttribute("name","foo");
  print $name, "\n";
}

$doc->printToFile ("out.xml");

#print $doc->toString;
