#!/bin/sh -
# This require Norm Walsh's dtdparse package:
# http://nwalsh.com/perl/dtdparse/

DTDPARSEDIR=$HOME/xml/dtdparse-2.0b2

perl $DTDPARSEDIR/dtdparse.pl --title "JavaML DTD" --output java-ml-dtd.xml java-ml.dtd && \
  perl $DTDPARSEDIR/dtdformat.pl --html java-ml-dtd.xml

# and the below documents the DTD using E. Hood's perlSGML-based dtd2html:
mkdir java-ml-dtd-html && cd java-ml-dtd-html && rm -f *
dtd2html ../java-ml.dtd
