#!/usr/bin/perl -w

use XML::DOM;

my $filename = shift @ARGV;

my $parser = new XML::DOM::Parser;
my $doc = $parser->parsefile ($filename);

# print all NAME attributes of all method elements
my $nodes = $doc->getElementsByTagName("method");
my $n = $nodes->getLength();

print "$n methods...\n";

for (my $i = 0; $i < $n; $i++) {	
  my $node = $nodes->item ($i);	
  my $name = $node->getAttribute("name");
#  $node->setAttribute("name","foo");
  print $name, "\n";
}

$doc->printToFile ("out.xml");

#print $doc->toString;
