#!/usr/bin/perl -w

use XML::DOM;

my $filename = shift @ARGV;

my $parser = new XML::DOM::Parser;
my $doc = $parser->parsefile ($filename);

# print all NAME attributes of all method elements
my $nodes = $doc->getElementsByTagName ("METHOD");
my $n = $nodes->getLength;

for (my $i = 0; $i < $n; $i++) {	
  my $node = $nodes->item ($i);	
  my $href = $node->getAttribute ("NAME");
  print $href->getValue . "\n";
}

$doc->printToFile ("out.xml");

print $doc->toString;
