ln -s ../archive/illustrator-portrait-poster.ai ./illustrator-portrait-poster.ai
ln -s . ./EDU
ln -s . ./foo
ln -s . ./grad
ln -s . ./Washington
ln -s . ./gjb
ln -s . ./cassowary
ln -s . ./classes
ln -s ../javaml-badros-www9.html ./paper/javaml.html
ln -s ../java-ml.dtd ./paper/java-ml.dtd
ln -s ../tex-paper/www9-submission.zip ./paper/www9-submission.zip
ln -s ../../bib/library.bib ./tex-paper/library.bib
ln -s ../../bib/applications.bib ./tex-paper/applications.bib
ln -s ../../bib/articles.bib ./tex-paper/articles.bib
ln -s ../java-ml.dtd ./tex-paper/java-ml.dtd
ln -s ../../java-ml.dtd ./examples/xml-unparsed/java-ml.dtd
ln -s . ./examples/voltage
ln -s . ./examples/LED
ln -s . ./examples/foo
ln -s . ./examples/cannon
ln -s . ./examples/casso-test/EDU
ln -s . ./examples/casso-test/grad
ln -s . ./examples/casso-test/Washington
ln -s . ./examples/casso-test/gjb
ln -s . ./examples/casso-test/cassowary
ln -s . ./examples/casso-test/classes
ln -s ../java-ml.dtd ./examples/casso-test/xml-unparsed/java-ml.dtd
ln -s ../java-ml.dtd ./examples/casso-test/java-ml.dtd
ln -s ../java-ml.dtd ./examples/java-ml.dtd
