#!/uns/bin/zsh -f
#set -x
setopt extendedglob
DIR=`date +%Y-%m-%d`
JHT=$JAVAML_HOME/tools
if [[ "gjb-xml-unparse" != `basename $PWD` ]]; then
  print -u2 "Wrong directory: cd gjb-xml-unparse"
  exit -1
fi

rm -f gjb-xml-unparse-*.patch(N)

pushd ..

for i in Makefile.in ast.h control.cpp jikes.cpp option.cpp option.h stream.h stream.cpp; do
  diff -u $HOME/jikes-1.11/src/$i $i >> gjb-xml-unparse-$DIR-against-1.11.patch
done

for i in Makefile.in ast.h control.cpp jikes.cpp option.cpp option.h stream.h stream.cpp; do
  diff -u $HOME/jikes-latest-clean/src/$i $i >> gjb-xml-unparse-$DIR-latest-cvs.patch
done

popd
mkdir -p JavaML
cp ../ChangeLog-JavaML ../gjb-xml-unparse-$DIR-*.patch ../README-JAVAML ../xml-unparse.cpp \
    .
cp  $JAVAML_HOME/java-ml.dtd $JHT/jikes-xml $JHT/cat-javaml \
    $JHT/javaml-to-plain-source.xsl \
    $JHT/javaml-to-html.xsl \
    $JHT/javaml-extract-comments.xsl \
    $JHT/results-to-plain-source \
    $JHT/javaml-{instrument,list-methods,to-html,to-plain-source,extract-comments} \
   JavaML

mkdir -p arch
tar czf arch/jikes-gjb-xml-unparse-$DIR.tar.gz JavaML *~make-new-dist(.)
scp arch/jikes-gjb-xml-unparse-$DIR.tar.gz saba:./ftp-gjb/code
